{% set name = "watchgod" %}
{% set version = "0.8.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: cb11ff66657befba94d828e3b622d5fb76f22fbda1376f355f3e6e51e97d9450

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - watchgod = watchgod.cli:cli


requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}
    - anyio >=3.0.0,<4

test:
  requires:
    - python {{ python_min }}
    - pip
  imports:
    - watchgod
  commands:
    - watchgod -h
    - pip check

about:
  home: https://github.com/samuelcolvin/watchgod
  summary: Simple, modern file watching and code reload in python.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - synapticarbors
